--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/chainsaw-man_2022-12-31_11:15/wallhaven-2ye9jm.jpg"

-- Special
background="#00000B"
foreground="#dee1e2"
cursor="#dee1e2"

-- Colors
color0="#00000B"
color1="#537C93"
color2="#339EB1"
color3="#678E9B"
color4="#64949B"
color5="#91A8A8"
color6="#B7C1C7"
color7="#dee1e2"
color8="#9b9d9e"
color9="#537C93"
color10="#339EB1"
color11="#678E9B"
color12="#64949B"
color13="#91A8A8"
color14="#B7C1C7"
color15="#dee1e2"
