#!/bin/sh
#   _________  _____  .______________
#  /   _____/ /  _  \ |   \_   _____/  Author:   Saif Shahriar
#  \_____  \ /  /_\  \|   ||    __)    Web:      https://saifshahriar.github.io/
#  /        /    |    |   ||     \     GitHub:   https://github.com/saifshahriar
# /_______  \____|__  |___|\___  /     GitLab:   https://gitlab.com/saifshahriar
#         \/        \/         \/      License:  MIT
#
# My first wayland compositor config. Everything should work fine. Needs to add
# up some things.

#################
### Variables ###
#################
terminal=foot
modkey=Super

##################
### Appearance ###
##################
# Set background and border color
riverctl background-color 0x1a1b26
riverctl border-color-focused 0xc0caf5
riverctl border-color-unfocused 0x586e75

riverctl border-width 2     # border pixel of windows

##################
### Behaviour ####
##################
riverctl set-cursor-warp on-focus-change
riverctl focus-follows-cursor always

####################
### Window Rules ###
####################
# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 1 -outer-padding 5 &

###################
### Keybindings ###
###################
## Basic Programmes
# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $modkey Return spawn $terminal

## Window Controls
# Focus next/prev window
riverctl map normal $modkey J focus-view next
riverctl map normal $modkey K focus-view previous
riverctl map normal Alt Tab focus-view next

# Move windows in stack
riverctl map normal $modkey+Shift J swap next
riverctl map normal $modkey+Shift K swap previous

# Swap master and slave window
riverctl map normal $modkey+Ctrl Return zoom

# Close the focused view
riverctl map normal $modkey C close

# Super+Shift+E to exit river
riverctl map normal $modkey+Shift q exit

# Decrease/increase the master window ratio
riverctl map normal $modkey H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $modkey L send-layout-cmd rivertile "main-ratio +0.05"

# Increment/decrement the number of master windows
riverctl map normal $modkey+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $modkey+Shift L send-layout-cmd rivertile "main-count -1"

### Monitor
# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal $modkey Period focus-output next
riverctl map normal $modkey Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $modkey+Shift Period send-to-output next
riverctl map normal $modkey+Shift Comma send-to-output previous

# Super + Left Mouse Button to move views
riverctl map-pointer normal $modkey BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal $modkey BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal $modkey BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))
    riverctl map normal $modkey $i set-focused-tags $tags
    riverctl map normal $modkey+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $modkey+Control $i toggle-focused-tags $tags

	# Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $modkey+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $modkey 0 set-focused-tags $all_tags
riverctl map normal $modkey+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal $modkey Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal $modkey F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $modkey Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $modkey Right send-layout-cmd rivertile "main-location right"
riverctl map normal $modkey Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $modkey Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal $modkey F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough $modkey F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'
    #Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
	
    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set keyboard repeat rate
riverctl set-repeat 50 300


# autostart
foot --server &
wlr-randr --output Virtual-1 --mode 1360x768 &
