import = [
	"~/.config/alacritty/fonts.toml",
	"~/.config/alacritty/colors.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 82, lines = 25 }
padding = { x = 20, y = 20 }
dynamic_padding = true
decorations = "full"
opacity = 0.9
blur = true
startup_mode = "Windowed"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[cursor]
style.blinking = "On"
blink_interval = 800
unfocused_hollow = true

[mouse]
hide_when_typing = true
bindings = [
	{ mouse = "Middle", action = "Paste" },
]

[keyboard]
bindings = [
	# Copy-Paste
	{ key = "c",      mods = "Control|Shift", action = "Copy" },
	{ key = "v",      mods = "Control|Shift", action = "Paste" },
	# Increase-Decrease Font Size
	{ key = "Period", mods = "Alt",           action = "IncreaseFontSize" },
	{ key = "Comma",  mods = "Alt",           action = "DecreaseFontSize" },
	{ key = "r",      mods = "Alt|Shift",     action = "ResetFontSize" },
	# Navigation
	{ key = "j",      mods = "Alt",           action = "ScrollLineDown" },
	{ key = "k",      mods = "Alt",           action = "ScrollLineUp" },
	{ key = "u",      mods = "Alt",           action = "ScrollPageUp" },
	{ key = "d",      mods = "Alt",           action = "ScrollPageDown" },
	{ key = "PageUp",                         action = "ScrollPageUp" },
	{ key = "PageDown",                       action = "ScrollPageDown" },
	{ key = "Home",                           action = "ScrollToTop" },
	{ key = "End",                            action = "ScrollToBottom" },
	# Window
	{ key = "Enter",  mods = "Control",       action = "CreateNewWindow" },
	# Vi Mode
	{ key = "e",      mods = "Control",       action = "ToggleViMode" },
	{ key = "o",      mode = "Vi",            action = "Open" },
]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
